### PR TITLE
Isoparametric Elements.

### PR DESCRIPTION
**Pull request by xuchen-han**
Add an abstract IsoparametricElement class for generic APIs for isoparametric FEM elements.
Add a concrete linear simplex element implementing the APIs.

---
This change is [Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5)

### CODE REVIEW

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
Very nice and clear code @xuchenhan-tri.

My main comment is that `IsoparametricElement` should be entirely independent of `Quadrature`, since at a high level they are different concepts.
To accomplish this, think of `IsoparametricElement` as a glorified functor of the variable xi. Then each of those method you have would have a `const std::vector<VectorD>& xi` as input argument. A user and even in units tests you then have the freedom to evaluate those shape functions wherever you want.

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-:-MJXLacV2tXyfTlypJY_:b-mgr7pz)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/dev/isoparametric_element.h, line 6 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXE4gbEIZthYPKLWzR:-MJXE4gbEIZthYPKLWzS:bi5dxz1) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L6)):*
> ```objc
> 
> #include "drake/common/eigen_types.h"
> #include "drake/multibody/fem/dev/quadrature.h"
> ```

I haven't seen the rest, but having `IsoparametricElement` depend on `Quadrature` rises a red flag in my mind. I believe they should not depend on each other.
___
*[multibody/fem/dev/isoparametric_element.h, line 14 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXEQLABlyKhzsXa7bq:-MJXEQLABlyKhzsXa7br:bqrd2j3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L14)):*
> the function we are solving for, ...

This class should know nothing about what we are solving for. I'd describe `IsoparametricElement` in terms of what it really is (or I believe it is); The defining characteristic of an isoparametric element is that the same shape functions used to define the mapping from the parent domain to the spatial domain, are used to define the interpolation of functions defined in the domain of the element.
___
*[multibody/fem/dev/isoparametric_element.h, line 18 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXFtf5CFXHiooQTjWL:-MJXFtf5CFXHiooQTjWM:b-646ut3) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L18)):*
> ```objc
> 
>         X(ξ) = Sₐ(ξ)Xₐ, and
>         u(ξ) = Sₐ(ξ)uₐ,
> ```

nice! I like this. Does this render as you imagined it on Doxygen? I usually place them in the pair `<pre>`/`</pre>`, not sure what happens if you dont.
___
*[multibody/fem/dev/isoparametric_element.h, line 34 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXGFyo56jiBFUR0yQu:-MJXGFyo56jiBFUR0yQv:bazgfhp) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L34)):*
> ```objc
>   */
>   explicit IsoparametricElement(const Quadrature<T, NaturalDim>& quadrature)
>       : quadrature_(quadrature) {}
> ```

this coupled IsoparametricElement to quadrature. Not sure we want this?
The way I think of shape functions is exactly what you wrote above, a function `Sₐ(ξ)` of `ξ`, which says nothing about quadratures. 
___
*[multibody/fem/dev/isoparametric_element.h, line 54 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXHGwU2dGcR0ptv6fl:-MJXHGwVA5unsAfsCLjW:b-hb9a0q) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L54)):*
> ```objc
>       component of S(ξ) corresponds to the shape function Sₐ(ξ) for node a.
>       @returns S Vector of size equal to the number of quadrature points in
>       `quadrature_`. The q-th entry of the output contains vector S(ξ), of size
> ```

private members cannot show up in public documentation.
___
*[multibody/fem/dev/isoparametric_element.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXGgAD8GQwiCSi81ME:-MJXGgAD8GQwiCSi81MF:b-niuycv) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L57)):*
> ```objc
>       num_nodes(), evaluated at the q-th quadrature point.
>   */
>   virtual const std::vector<VectorX<T>>& CalcShapeFunctions() const = 0;
> ```

In the snippet we drafted together we wrote this:
```c++
/// Computes the shape function vector S(ξ) = [S₁(ξ); S₂(ξ)...Sₐ(ξ)...Sₙ(ξ)]
  /// at each quadrature point specified by `quadrature`. The a-th component
  /// of S(ξ) corresponds to the shape function Sₐ(ξ) for node a,
  /// a < num_nodes().
  /// @param quadrature Specifies the quadrature points ξq at which to evaluate
  /// the shape funcrtions.
  /// @param S Vector of size quadrature.num_quadrature_points(). On output
  /// element q contains vector S(ξ), of size num_nodes(), evaluated at the q-th
  /// quadrature point quadrature.point(q).
  virtual void CalcShapeFunctions(const Quadrature<T>& quadrature,
                                  std::vector<VectorX<T>>* Sa_xiq) const = 0;

```

which takes quadrature as an argument. This has the nice side effect of modularity, i.e. `IsoparametricElement` does not depend on `Quadrature` and viceversa.
From an abstraction point of view, it does seem to represent IsoparametricElement as this collection of shape functions `Sₐ(ξ)` at each local node `a`.

Is there a reason you prefer `IsoparametricElement` to depend on `Quadrature`?


Another possibility, possibly more general, would be the signature:
```c++
virtual void CalcShapeFunctions(const std::vector<VectorD>& xi,
                                  std::vector<VectorX<T>>* Sa_xiq) const = 0;
```

Which says nothing about the nature of `xi`, allowing it to be completely arbitrary, not just a specific quadrature point. For quadratures, we'd just pass `quadrature.get_points()`, which has the same type.

In retrospect, I believe this is what we want. Notice that in this way the concept `Sₐ(ξ)` is nicely captured and it shows up in the code in the fact that we don't even need to include the quadrature header or use some forward declaration trick. Then `IsoparametricElement` is fully independent of `Quadrature`. Your unit tests would not depend on quadratures and would be simpler.
___
*[multibody/fem/dev/isoparametric_element.h, line 69 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXJjTMC71onjD5FyNu:-MJXJjTMC71onjD5FyNv:b-8i0bda) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L69)):*
> ```objc
>       the q-th quadrature point.
>   */
>   virtual const std::vector<MatrixX<T>>& CalcGradientInParentCoordinates()
> ```

do we want a signature for gradients in spatial coordinates?
___
*[multibody/fem/dev/isoparametric_element.cc, line 15 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXKOYhEGQWIMJxYyxy:-MJXKOYhEGQWIMJxYyxz:b-75kf31) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L15)):*
> ```cpp
>   DRAKE_DEMAND(xa.cols() == num_nodes());
>   std::vector<MatrixX<T>> J(num_quads());
>   const auto& dSdxi = CalcGradientInParentCoordinates();
> ```

per GSG, spell out type.
___
*[multibody/fem/dev/isoparametric_element.cc, line 58 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXKctA2Qa8Lj5Hla5c:-MJXKctA2Qa8Lj5Hla5d:bcu0nsr) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L58)):*
> ```cpp
> template <typename T, int NaturalDim>
> std::vector<T> IsoparametricElement<T, NaturalDim>::InterpolateScalar(
>     const Eigen::Ref<const VectorX<T>>& ua) const {
> ```

here you could also have `const std::vector<VectorD>& xi` as the list of natural coordinate where you'd like to interpolate u. It also decouples from `Quadrature`. 
___
*[multibody/fem/dev/isoparametric_element.cc, line 75 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXL4eh3kwA0QqjVyuy:-MJXL4eh3kwA0QqjVyuz:bsql9a9) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L75)):*
> ```cpp
>   std::vector<VectorX<T>> interpolated_value(num_quads());
>   for (int q = 0; q < num_quads(); ++q) {
>     interpolated_value[q] = ua * S[q];
> ```

very nice, I love how compact this looks!
___
*[multibody/fem/dev/isoparametric_element.cc, line 81 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXLE_t2DgDPAy7jdC1:-MJXLE_t2DgDPAy7jdC2:b-rqf344) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L81)):*
> ```cpp
> 
> template class IsoparametricElement<double, 2>;
> template class IsoparametricElement<double, 3>;
> ```

we'd like to make sure our code is AutoDiffXd compatible, the main reason to have this template `T` everywhere. Let's instantiate on `AutoDiffXd` whenever possible.

**Review by xuchen-han — COMMENTED** [review]
I see your point that `IsoparametricElement` should be entirely independent of `Quadrature`. I propose to move `const std::vector<VectorD>& xi` from the input arguments to the constructor to facilitates precomputes. I would argue that we are not losing the freedom to evaluate at other locations because we can simply instantiate another isoparametric element that takes another set of `xi` at construction. Maybe we should discuss this f2f.

I went through all of your comments. All are well-received and my response to all are "Will do". Thanks!

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-:-MJ_UiYf8w2JbyZcBNQ6:behcoh5)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/dev/isoparametric_element.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXGgAD8GQwiCSi81ME:-MJ_TVRJAWSBq8JQKBQ5:bw6jjyj) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L57)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

In the snippet we drafted together we wrote this:
```c++
/// Computes the shape function vector S(ξ) = [S₁(ξ); S₂(ξ)...Sₐ(ξ)...Sₙ(ξ)]
  /// at each quadrature point specified by `quadrature`. The a-th component
  /// of S(ξ) corresponds to the shape function Sₐ(ξ) for node a,
  /// a < num_nodes().
  /// @param quadrature Specifies the quadrature points ξq at which to evaluate
  /// the shape funcrtions.
  /// @param S Vector of size quadrature.num_quadrature_points(). On output
  /// element q contains vector S(ξ), of size num_nodes(), evaluated at the q-th
  /// quadrature point quadrature.point(q).
  virtual void CalcShapeFunctions(const Quadrature<T>& quadrature,
                                  std::vector<VectorX<T>>* Sa_xiq) const = 0;

```

which takes quadrature as an argument. This has the nice side effect of modularity, i.e. `IsoparametricElement` does not depend on `Quadrature` and viceversa.
From an abstraction point of view, it does seem to represent IsoparametricElement as this collection of shape functions `Sₐ(ξ)` at each local node `a`.

Is there a reason you prefer `IsoparametricElement` to depend on `Quadrature`?


Another possibility, possibly more general, would be the signature:
```c++
virtual void CalcShapeFunctions(const std::vector<VectorD>& xi,
                                  std::vector<VectorX<T>>* Sa_xiq) const = 0;
```

Which says nothing about the nature of `xi`, allowing it to be completely arbitrary, not just a specific quadrature point. For quadratures, we'd just pass `quadrature.get_points()`, which has the same type.

In retrospect, I believe this is what we want. Notice that in this way the concept `Sₐ(ξ)` is nicely captured and it shows up in the code in the fact that we don't even need to include the quadrature header or use some forward declaration trick. Then `IsoparametricElement` is fully independent of `Quadrature`. Your unit tests would not depend on quadratures and would be simpler.
</blockquote></details>

I see your point that IsoparametricElement should not depend on Quadrature; however, I want to communicate to the constructor where we are going to evaluate everything (shape function, gradient, jacobian etc) for the following reason:
1) We would have `const std::vector<VectorD>& xi` appearing in every function's argument and they are the same location more often than not. So It seems cleaner to move that to the constructor and have the isoparametric element only evaluate at those locations. If we want to evaluate at another location, just create another element instance.
2) More importantly, knowing the position at which to evaluate facilitates precomputes for quantities that only depend on `xi`.
___
*[multibody/fem/dev/isoparametric_element.h, line 69 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXJjTMC71onjD5FyNu:-MJ_UO7-ANr1_NIAIiwA:b5mpnhh) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L69)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we want a signature for gradients in spatial coordinates?
</blockquote></details>

Surprisingly, I didn't find the need in my FEM demo (yet). I will add it if you think it completes the picture.

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/dev/isoparametric_element.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXGgAD8GQwiCSi81ME:-MJb6COZBJ7MOpvgPzAN:bphm86y) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L57)):*
> We would have const std::vector<VectorD>& xi appearing in every function's argument and they are the same location more often than not

IMO that is actually a feature that communicates better where the evaluation happens. Similarly to a functor you'd evaluate at a particular argument. Not strong about it, but if this  "convenience argument" should not be the deciding factor.


>  knowing the position at which to evaluate facilitates precomputes for quantities that only depend on xi.

As far as I understand it, that pre-computation is a one-time cost that would happen once at the beginning of the simulation. Also, it's very cheap compared to everything else. So definitely I don't see any gain.


I only present the two points above so you have them. IMO 1 and 2 are not good deciding factors on whether to place that argument in the ctor or not. 
It might be you have point (3) "I just like it better", and I that is also a valid argument. My preference?: argument at the functions, since the methods in `IsoparametricElement` "read" as functions of `xi`. But since the use of this class is very local, I can see how you like the ctor option better.
___
*[multibody/fem/dev/isoparametric_element.cc, line 36 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXR7jvAXI9McmE2XM2:-MJXR7jvAXI9McmE2XM3:b-3lti5t) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L36)):*
> ```cpp
> template <typename T, int NaturalDim>
> std::vector<MatrixX<T>>
> IsoparametricElement<T, NaturalDim>::CalcElementJacobianInverse(
> ```

btw, this code will require unit testing (you might have it though). Now, when do you foresee to use it? do we need gradients on a manifold in the foreseeable future? What I am trying to say is that it is ok if the default implementation just throws when `nsd != NaturalDim` and it might simplify your PR. 
But ok if you already wrote it and want it there.

**Review by amcastro-tri — COMMENTED** [review]
Thank you for your patience Xuchen. I really appreciate your hard work and dedication. Can't wait to see this landed!

> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-:-MJb85vE1UJ7xol9AddJ:b-krpvoj)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/xuchenhan-tri/drake/5)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @xuchenhan-tri)

___
*[multibody/fem/dev/isoparametric_element.h, line 57 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXGgAD8GQwiCSi81ME:-MJbohgo6f1FzA7EpIdE:blde3b7) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.h#L57)):*
Let me try to be more specific on point 2. For example, I need `dSdxi` in the computation of the stiffness matrix and that is in the inner loop and definitely not a one time thing. So when you said 

> [T]hat pre-computation is a one-time cost that would happen once at the beginning of the simulation. 

do you mean to calculate `dSdxi` at the beginning of the simulation and store the result in the FemElement?

I retract my point 1 and regarding point 3, I don't have a strong preference. My main concern is the efficiency/precompute.
___
*[multibody/fem/dev/isoparametric_element.cc, line 36 at r1](https://reviewable.io/reviews/xuchenhan-tri/drake/5#-MJXR7jvAXI9McmE2XM2:-MJbpvUUE6rRsG90zZVO:b-e4tq4o) ([raw file](https://github.com/xuchenhan-tri/drake/blob/cb4484b66cebcc9c641cdc29c22a4a865f060cdb/multibody/fem/dev/isoparametric_element.cc#L36)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

btw, this code will require unit testing (you might have it though). Now, when do you foresee to use it? do we need gradients on a manifold in the foreseeable future? What I am trying to say is that it is ok if the default implementation just throws when `nsd != NaturalDim` and it might simplify your PR. 
But ok if you already wrote it and want it there.
</blockquote></details>

I do have a unit test for this function. I need the Jacobian inverse (as a precompute) for calculating the deformation gradient. 

We would need this on the manifold if we want the deformation gradient of, say, a piece of cloth. I already have the implementation for `nsd >= NaturalDim`, and I just realized that I should throw if `nsd < NaturalDim`.

**Pull request closed without merging**
